export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_NOT_VERIFIED: "AUTH_ACCOUNT_NOT_VERIFIED",
  AUTH_VERIFICATION_TOKEN_NOT_FOUND: "AUTH_VERIFICATION_TOKEN_NOT_FOUND",
  AUTH_VERIFICATION_TOKEN_EXPIRED: "AUTH_VERIFICATION_TOKEN_EXPIRED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
