export const ErrorCode = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_VERIFICATION_TOKEN_NOT_FOUND: "AUTH_VERIFICATION_TOKEN_NOT_FOUND",
  AUTH_VERIFICATION_TOKEN_EXPIRED: "AUTH_VERIFICATION_TOKEN_EXPIRED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
